version: '3.2'
services:
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus:/etc/prometheus/
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
        restart: always
        depends_on:
            - alertmanager

    blackbox-exporter:
        image: prom/blackbox-exporter
        ports:
            - 9115:9115
        restart: always
        volumes:
            - ./blackbox:/config
        command: --config.file=/config/blackbox.yml

    alertmanager-bot:
        command:
            - --alertmanager.url=http://62.84.124.122:9093
            - --log.level=info
            - --store=bolt
            - --bolt.path=/data/bot.db
        environment:
          TELEGRAM_ADMIN: "-1001598110020"
          TELEGRAM_TOKEN: 5182326485:AAHrshec7_4VQjU2pjeDni1kR7j9lfnxfz4
        image: metalmatze/alertmanager-bot:0.4.3
        ports:
        - 8080:8080
        user: "0"
        restart: always
        volumes:
        - ./data:/data

    alertmanager:
        image: prom/alertmanager:v0.21.0
        ports:
           - 9093:9093
        volumes:
           - ./alertmanager/:/etc/alertmanager/
        user: "0"
        restart: always
        command:
           - '--config.file=/etc/alertmanager/config.yml'
           - '--storage.path=/etc/alertmanager/data'

    node-exporter:
        image: prom/node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        hostname: monitoring
        command:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        ports:
            - 127.0.0.1:9100:9100
        restart: always
    grafana:
        image: grafana/grafana
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        volumes:
            - ./grafana:/var/lib/grafana
            - ./grafana/provisioning/:/etc/grafana/provisioning/
        user: "0"
        restart: always